# Site
title: Dondi De Ocampo
subtitle: Personal Sandbox
description: A technologist in the IoT space, interested in the "ilities" and the ways to enable them ... This is a very informal, free flowing site of ideas and code that Iâ€™ve used to learn and enjoy software. 
author: Dondi De Ocampo
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://deocampo.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Theme
theme: jekyll-theme-minimal
